name: Java build

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Build and test
        run: |
          mvn clean install --quiet
          mvn test --quiet

  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run check style
        uses: nikitasavinov/checkstyle-action@master
        with:
          level: 'Error'
          reporter: 'github-pr-check'
          checkstyle_config: 'sun_checks.xml'
          fail_on_error: true